server:
  port: 8080
spring:
  # JPA 相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
#      prefix: /views/
      suffix: .jsp
      prefix:  /
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/analyzer?serverTimezone=GMT%2B8&amp
    username: briup
    password: briup
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
# # config-location: classpath:mybatis-config.xml
#  typeAliasesPackage: com.analyzer.dao.*
# # mapperLocations: classpath:resources/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
supportMethodsArguments: true
params: count=countSql
#logging:
 # config: classpath:logback.xml
  #配置日志文件路径
  #level:
  #  xatu.zsl: debug #不同目录下的日志可配置不同级别
  # org.springfromework.web: info
  # org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  #file: log/myspringboot.log